import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useDispatch, useSelector } from "react-redux";
import { useEffect, useRef } from "react";
import * as userSlice from "../slices/userSlice";
import { userState } from "../slices/userSlice";
import { AppDispatch, wrapper } from "../store/store";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const users = useRef(false);
  const dispatch = useDispatch<AppDispatch>();
  const result: userState = useSelector(userSlice.getUsersState);
  useEffect(() => {
    //since here useEffects runs two times
    if (users.current === false) {
      dispatch(userSlice.fetchUsers());
    }
    //component unmounts
    return () => {
      users.current = true;
    };
  }, []);

  function handleClick() {
    dispatch(userSlice.increment({ value: 2 }));
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {result.users.map((item: any, index: any) => {
          return <h1 key={index}>{item.company.name}</h1>;
        })}
        <button onClick={handleClick}>Increment</button>
        <h1>{result.value}</h1>
      </main>
    </>
  );
}

// export const getServerSideProps = wrapper.getServerSideProps(
//   (store): any =>
//     async () => {
//       store.dispatch(userSlice.fetchUsers());
//     }
// );
